apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suricata.fullname" . }}
  labels: 
    app: {{ template "suricata.name" . }}-updater
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ template "suricata.fullname" . }}
  labels:
    app: {{ template "suricata.name" . }}-updater
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - pods/log
  verbs:
    - get
    - list
- apiGroups:
    - ""
  resources:
    - "pods/exec"
  verbs:
    - "create"
    
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "suricata.fullname" . }}
  labels:
    app: {{ template "suricata.name" . }}-updater
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "suricata.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "suricata.fullname" . }}