apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations: {}
  labels:
    created-by: {{ template "suricata.name" . }}-update
    name: {{ template "suricata.fullname" . }}-rules-pvc
  name: {{ template "suricata.fullname" . }}-rules-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: edcop-nfs
  resources:
    requests:
      storage: 5Gi